language: python

addons:
    mariadb: '15.1'
    ssh_known_hosts: 104.236.112.220

install:
    - pip install -r requirements.txt
    - ./manage.py --config testing create-db -u root

script:
    - ./manage.py test 
    - make -C docs/ html

before_install:
    - openssl aes-256-cbc -K $encrypted_e1f40c693a59_key -iv $encrypted_e1f40c693a59_iv -in deploy_key.enc -out deploy_key -d

after_success:
    - bash <(curl -s https://codecov.io/bash)
    - bash scripts/deploy.sh

notifications:
    email: false # SHUT UP TRAVIS
